add_newline = true

[[battery.display]]
threshold = 30

[character]
vicmd_symbol = "ğŸ¥ "

[custom.fennel]
command = "fennel -v"
symbol = "ğŸ§… "
extensions = ["fnl"]

[custom.racket]
command = """echo `racket -v` | awk '{ print $4 " " $5 }' | sed 's/.$//'"""
symbol = "ï¬¦|ï¤œ "
extensions = ["rkt", "rktl"]

[custom.haskell]
symbol = "î· "
extensions = ["hs", "lhs"]
files = ["stack.yaml"]
